### ISSUE TITLE
Include `wp-includes/compat.php`

### ISSUE THREAD

**Issue by swissspidy** [php-stubs/wordpress-stubs#100]
Right now [compat functions WordPress ships with](https://github.com/WordPress/wordpress-develop/blob/6eda6f0825a38f4bf1498abd24e492d0a80cfa0f/src/wp-includes/compat.php), such as `str_contains`, are excluded from the stubs.

That means when a project's PHP version is < 8.0, PHPStan thinks the function does not exist and will report an error, even though WP actually provides this compat version

I can of course simply ignore the error in my config, but in my quick testing it seems like it should possible to include `wp-includes/compat.php` in the stubs, so that PHPStan will pick them up— as long as they are all still wrapped in `function_exists()` checks

Previously/related: #20 (though `readonly` is special because it's a syntax clash

**Comment by szepeviktor** [comment]
Hello Pascal!

A clash of technology and humans!!
We need a businessman 🕴🏻

**Comment by szepeviktor** [comment]
> wrapped in `function_exists()` checks

I am not able to do this. Very sorry. 🤮 This would make me vomit every day. Really. Not just saying it.

**Comment by szepeviktor** [comment]
I tolerate many legacy technologies in WordPress but there must be a red line.

**Comment by szepeviktor** [comment]
I am so sorry. This punches me right in the stomach.

Cannot help my feelings.

**Comment by szepeviktor** [comment]
What do you think?

**Comment by szepeviktor** [comment]
> That means when a project's PHP version is < 8.0, PHPStan thinks

There is [a cure](https://phpstan.org/config-reference#phpversion) for that :)

```
parameters:
    phpVersion: 80000
```

**Comment by swissspidy** [comment]
> Could you include this file in your project?
> Maybe not the whole file only this function.

Sure, I could do that.

However, I don't think it makes sense for every plugin/theme to manually include a copy of the `wp-includes/compat.php` file when they are already using the WP stubs. I would expect the stubs to be a representation of the environment my project runs in and include this polyfill

Would you accept a PR for this?

**Comment by szepeviktor** [comment]
I am sorry. For emotional reasons I'm not able to maintain this project any more with more-and-more legacy technologies.

But I'm open to add an extra file in the root of this project with some instructions.
```neon
parameters:
    scanFiles:
        - vendor/php-stubs/wordpress-stubs/compat.php
```

What do you think about this compromise?

**Comment by szepeviktor** [comment]
Okay! I give it up.
I will merge your PR with 1 condition: I will not look at the code.

Is it okay for you?

**Comment by szepeviktor** [comment]
@swissspidy Are you ready for a blind PR?

**Comment by swissspidy** [comment]
Looks like this would require changes to `visitor.php` as well because the functions are all wrapped in `function_exists()` checks. I don't have the time right now to look into it.

**Comment by szepeviktor** [comment]
> functions are all wrapped in `function_exists()` checks.

That feels normal for WordPress people but really Freaks me out.
I strongly encourage you too to leave legacy technologies behind today.
https://github.com/szepeviktor/starter-plugin/blob/master/README.md#what-to-avoid
