### ISSUE TITLE
`wp_is_development_mode()` is missing from the stubs

### ISSUE THREAD

**Issue by jacobcassidy** [php-stubs/wordpress-stubs#103]
Title says it all. `wp_is_development_mode()` is missing from the stubs.

**Comment by szepeviktor** [comment]
Oh nooo!
I have to investigate ... 🕵🏻‍♂️

**Comment by szepeviktor** [comment]
@jacobcassidy It has been renamed: https://github.com/WordPress/WordPress/commit/018821ff9a1dcca53ed5e4f589b0396656c87668

**Comment by jacobcassidy** [comment]
@szepeviktor Sneaky change lol

**Comment by szepeviktor** [comment]
Strange news: it is in wordpress-stubs.php

**Comment by jacobcassidy** [comment]
Interesting, it doesn't show up in the search in this repo. GitHub must not search files that are too large to display unless in raw mode.
