### ISSUE TITLE
wp_insert_attachment doesn't show WP_Error as possible return value

### ISSUE THREAD

**Issue by danieliser** [php-stubs/wordpress-stubs#107]
```php
$attach_id = wp_insert_attachment( $attachment, $file_path );

if ( is_wp_error( $attach_id ) ) {

}
```

```
is_wp_error(int<0, max>) will always evaluate to false.
```

```
@var int|\WP_Error $attach_id
PHPStan: int<0, max> $attach_id
```

**Comment by szepeviktor** [comment]
Hello @danieliser 👋🏻 

We have all luxury for `wp_insert_attachment`
https://github.com/search?q=repo%3Aphp-stubs%2Fwordpress-stubs%20wp_insert_attachment&type=code

What is the docblock in your stubs file?

**Comment by szepeviktor** [comment]
Try
```php
$attach_id = wp_insert_attachment( $attachment, $file_path, true );
```

**Comment by johnbillion** [comment]
Yeah this is working as expected. As Viktor pointed out, a `WP_Error` is only returned if the `$wp_error` parameter is true.

Ref: https://github.com/php-stubs/wordpress-stubs/blob/e53228ea81386cd9332127da9cb5a05e3d8dcc34/functionMap.php#L106

**Comment by danieliser** [comment]
@johnbillion @szepeviktor - Wow great catch, thanks. Easy fix at least.

**Comment by danieliser** [comment]
@szepeviktor - Just want to correct this for the record, its the 4th arg for $wp_error

```
$attach_id = wp_insert_attachment( $attachment, $file_path, 0, true );
```
