### ISSUE TITLE
Add "require" packages

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#11]
- php >= 5.6
- "suggest"? ext-sodium
- phpmailer/phpmailer 6.1.6
- and exclude `wp-includes/PHPMailer`

Problem: this is only for v5.5.0+

**Comment by johnbillion** [comment]
I don't think any of these should be included. This library provides non-functional stubs of symbols from WordPress core, there should be no connection between the requirements of WordPress itself and the requirements of this library.
