### ISSUE TITLE
6.4 new see tag

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#114]
```diff
-         * @param array   $args              An array of arguments. @see wp_terms_checklist()
+         * @param array   $args              An array of arguments. See {@see wp_terms_checklist()}.
```

It makes phpstan-param tag disappear.
@johnbillion Please help me. You are WordPress for me.

https://github.com/php-stubs/wordpress-stubs/commit/1ad360f8519773e0cce1658d5f443212ee4dc6ad 👀

**Comment by johnbillion** [comment]
This is where this needs updating: https://github.com/php-stubs/wordpress-stubs/blob/547df0464816519e46cb47d6843cbc908eada290/visitor.php#L606-L609 . I won't have time to look at it this week.

**Comment by szepeviktor** [comment]
Thank you.
All right. I power down the Internet until you modify that line ❌🔋

Do you have a contact who can patch it in core?

**Comment by szepeviktor** [comment]
Thank you Ian.
https://github.com/php-stubs/wordpress-stubs/compare/master...6.4

**Comment by IanDelMar** [comment]
`@see` also prevented some phpstan-param tags in previous versions. With the fix, they will now appear.

https://github.com/php-stubs/wordpress-stubs/compare/master...6.4#diff-4dc94858ed12d457b90cbe75a4151de2b69d60a4693fc574a0bf8d4b71923f31R120726-R120745

**Comment by szepeviktor** [comment]
no 6.4 yet https://github.com/johnpbloch/wordpress/tags

**Comment by IanDelMar** [comment]
7 Nov: https://make.wordpress.org/core/6-4/

**Comment by szepeviktor** [comment]
I think it is fixed in the latest release. I am not sure.
