### ISSUE TITLE
Add type declarations to WP_Widget methods

### ISSUE THREAD

**Issue by benhickson** [php-stubs/wordpress-stubs#14]
I'm using [intelephense with VS Code](https://github.com/bmewburn/vscode-intelephense) and am aiming to add [type declarations](https://www.php.net/manual/en/language.types.declarations.php) to my widget methods. Intelephense supposedly uses this repo for its wordpress stubs.

When I add a type to my `form` method, I get an error, because the stubs don't have types.

For example:
```php
/**
 * Creates the backend form in the customizer
 */
public function form(array $instance): string {
  // echo stuff to create the form
  return '';
}
```
Shows the error:
```
Intelephense: Method 'My_Widget::form()' is not compatible with method 'WP_Widget::form()'
```

May I submit a PR with types added to at least these widget methods?

**Comment by szepeviktor** [comment]
Hello Ben! Thank you for your report.
This packages relies on the WordPress source.
Please send any changes there as I am not able to carry patches :(

**Comment by szepeviktor** [comment]
BTW WordPress core won't have typehints like `: string` because it is a PHP 7.x feature.

**Comment by benhickson** [comment]
Ahok. Gotcha!

**Comment by szepeviktor** [comment]
People - including me - insert a dirt-hiding-OOP layer between their code and WordPress core.

- https://github.com/szepeviktor/Toolkit4WP
- https://github.com/szepeviktor/small-project/blob/master/src/Config.php#L18
