### ISSUE TITLE
stubs for wpdb::get_row() and wpdb::get_results() are wrong

### ISSUE THREAD

**Issue by herndlm** [php-stubs/wordpress-stubs#143]
I think we should have the following

```patch
--- a/tests/data/wpdb.php
+++ b/tests/data/wpdb.php
@@ -10,12 +10,12 @@ use function PHPStan\Testing\assertType;
 // wpdb::get_row()
 assertType('stdClass|void|null', wpdb::get_row());
 assertType('stdClass|void|null', wpdb::get_row(null, 'OBJECT'));
-assertType('array<string, mixed>|void|null', wpdb::get_row(null, 'ARRAY_A'));
-assertType('array<int, mixed>|void|null', wpdb::get_row(null, 'ARRAY_N'));
+assertType('array<mixed>|void|null', wpdb::get_row(null, 'ARRAY_A'));
+assertType('list<mixed>|void|null', wpdb::get_row(null, 'ARRAY_N'));

 // wpdb::get_results()
 assertType('stdClass|null', wpdb::get_results());
 assertType('stdClass|null', wpdb::get_results(null, 'OBJECT'));
-assertType('array<string, stdClass>|null', wpdb::get_results(null, 'OBJECT_K'));
-assertType('array<string, mixed>|null', wpdb::get_results(null, 'ARRAY_A'));
-assertType('array<int, mixed>|null', wpdb::get_results(null, 'ARRAY_N'));
+assertType('stdClass|null', wpdb::get_results(null, 'OBJECT_K'));
+assertType('list<array<mixed>>|null', wpdb::get_results(null, 'ARRAY_A'));
+assertType('list<list<mixed>>|null', wpdb::get_results(null, 'ARRAY_N'));
```

the changes for get_row() are just improvements:
- I would use `array<mixed>` instead of `array<string, mixed>` because the keys will be int if they are numeric-strings
- list<mixed> is a narrower type that is also correct

get_results() on the other hand has a fix:
- ~~it seems to never return an object, WP is lying there. it always returns an array of rows and the rows are either object or array~~ sorry my bad, this is not true
- it also returns an object for OBJECT_K
- the rest are the same improvements as mentioned above

bonus improvement:
- the `null` return type is interesting. according to code and some playing around it seems to only occur if either the $query arg is `null` or the $output arg is invalid (none of the supported output "modes"). I don't consider this important.

briefly tried fixing it myself, but failed, too much magic already and I ran out of time :)

**Comment by herndlm** [comment]
forgot the screenshots I took when testing via debugger locally:

ARRAY_A:
![image](https://github.com/php-stubs/wordpress-stubs/assets/5738896/a728d5a5-daa5-4e41-b673-db1bb6b59056)


OBJECT_K:
![image](https://github.com/php-stubs/wordpress-stubs/assets/5738896/9257f86a-db92-4a15-ae83-c5ef74d15704)

ARRAY_N:
![image](https://github.com/php-stubs/wordpress-stubs/assets/5738896/d78fa3c5-37bb-4054-ab90-f9df5edb754e)

OBJECT:
![image](https://github.com/php-stubs/wordpress-stubs/assets/5738896/30dc75f4-bbc4-443d-b6db-8778bdc61b15)

**Comment by szepeviktor** [comment]
Thank you.

> get_results() on the other hand has a fix:
> 
>     * it seems to never return an object, WP is lying there. it always returns an array of rows and the rows are either object or array

@johnbillion Should we uncover this lie?

**Comment by herndlm** [comment]
> Thank you.
> 
> > get_results() on the other hand has a fix:
> > 
> > * it seems to never return an object, WP is lying there. it always returns an array of rows and the rows are either object or array
> 
> @johnbillion Should we uncover this lie?

wait, I was wrong, it does return an object 🤦‍♂️

**Comment by szepeviktor** [comment]
I think we are better off with closed eyes 🙈

**Comment by herndlm** [comment]
that was a bad start, sorry :D I adapted the issue. but this needs multiple checks, yeah. at least the screenshots are real and useful :)

**Comment by szepeviktor** [comment]
I just do not want to see the words "integer keyed object" on my screen.

**Comment by szepeviktor** [comment]
![image](https://github.com/php-stubs/wordpress-stubs/assets/952007/b7e17f84-6e8c-4fa1-9e47-9a891f14b000)

**Comment by herndlm** [comment]
yeah, no worries, I'll open a PR

**Comment by herndlm** [comment]
Phpstorm/xdebug threw me off, it is an array in all cases after all. With the latest stubs I get false positives. Will open a clean fix PR tomorrow with better explanations.

**Comment by IanDelMar** [comment]
This one is on me...
