### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by GiacoCorsiglia** [php-stubs/wordpress-stubs#149]
Hi @szepeviktor,

Once in a rare while I check on the status of this project, and it always brings me joy.  I did so today—and found that the stubs have been downloaded millions of times!  When I initially published [GiacoCorsiglia/wordpress-stubs](https://github.com/GiacoCorsiglia/wordpress-stubs) and the [generator](https://github.com/GiacoCorsiglia/php-stubs-generator), I didn't really expect anyone to use them, but turns out lots of people do.

I thought I should reach out with an overdue "thank you" for taking over the project, and for growing and maintaining it.  I haven't used WordPress (or PHP) in a long time, but I'm grateful that someone put in the time to make this project useful for the community.  Thank you, it's cool to see.

All the best,
Giaco

**Comment by szepeviktor** [comment]
Thank you for your kind words, Giaco.
