### ISSUE TITLE
 function wp_remote_retrieve_header expects array|WP_Error, httpReturnType given.

### ISSUE THREAD

**Issue by MocioF** [php-stubs/wordpress-stubs#150]
Hi,
I'm using wordpress-stubs with PHPStan for a plugin.
One of my methods returns the result of `wp_remote_get() `so I wrote in its phpdoc's comment:
`@return httpReturnType|WP_Error`

Now when I use the returned value in another method calling `wp_remote_retrieve_header`
PHPStan says
`Parameter #1 $response of function wp_remote_retrieve_header expects array|WP_Error, httpReturnType given.`

Why httpReturnType is not seen as an array?

**Comment by szepeviktor** [comment]
Hello @MocioF!

Thank you for your report.

There is no `httpReturnType` type. That variable holds an array shape.
Please write that array shape into your method.
https://github.com/php-stubs/wordpress-stubs/blob/5b0b62320bf41013db4cea68426ab2b959abaa28/functionMap.php#L5

**Comment by MocioF** [comment]
Thanks @szepeviktor , this is what I'm doing now.
Not sure if this can help, but now PHPStan says: ` Class WP_Http_Cookie referenced with incorrect case: WP_HTTP_Cookie`.

**Comment by szepeviktor** [comment]
> `Class WP_Http_Cookie referenced with incorrect case: WP_HTTP_Cookie`.

That is an error.

https://github.com/php-stubs/wordpress-stubs/blob/5b0b62320bf41013db4cea68426ab2b959abaa28/functionMap.php#L5-L9

Would you like to send a PR?
