### ISSUE TITLE
Issue with wp_get_global_stylesheet Function Not Recognized by Intelliphense

### ISSUE THREAD

**Issue by S-Blank** [php-stubs/wordpress-stubs#152]
### Description
I'm experiencing an issue where the WordPress function `wp_get_global_stylesheet` is not recognized by Intelliphense in my development environment.

### Steps to Reproduce
1. Include WordPress stubs in the project.
2. Use the `wp_get_global_stylesheet` function in the code.
3. Observe that Intelliphense marks this function as undefined.

### Expected behavior
Intelliphense should recognize the `wp_get_global_stylesheet` function and provide relevant IntelliSense features such as auto-completion and function documentation.

### Actual behavior
The function `wp_get_global_stylesheet` is marked as undefined by Intelliphense.

### System information
- **Operating System**: macOS Sonoma
- **Intelliphense Version**: v1.10.2
- **WordPress Version**: 6.4.2
- **Visual Studio Code Version**: 1.85.1 (Universal)

**Comment by szepeviktor** [comment]
Thank you for your report.
That function is on line 111534.
What is your stubs' version?

**Comment by johnbillion** [comment]
I think this can be closed, there's nothing different or incorrect about that function definition. It could be an issue with caching, intelephense still indexing the project, etc, etc.
