### ISSUE TITLE
The nice present: core phpstan tags vs. our phpstan tags in WordPress 6.5

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#163]
> Needs change in functionMap.php

@IanDelMar 

Stop adding our tag if a tag with the same name is already present.

https://github.com/php-stubs/wordpress-stubs/blob/794559556de631c52b98349890956d306ac38884/visitor.php#L402

What is to be fixed?
https://github.com/php-stubs/wordpress-stubs/pull/162/commits/6ef2cf0ab49fdf2c98ebfb53c4c41994e43e573d

**Comment by szepeviktor** [comment]
@johnbillion Has core started adding `@phpstan-*` tags in 6.5?

**Comment by johnbillion** [comment]
Nope

**Comment by szepeviktor** [comment]
So we could have these collisions in earlier stubs?

**Comment by IanDelMar** [comment]
Some @phpstan-tag annotations are now appearing because someone made changes to the core doc comment, allowing the node visitor to handle the doc comment without functionMap.php.

**Comment by IanDelMar** [comment]
> Some @phpstan-tag annotations are now appearing because someone made changes to the core doc comment, allowing the node visitor to handle the doc comment without functionMap.php.

But I thought we had checks for the functionMap.php already in place to catch such things.

**Comment by szepeviktor** [comment]
Do any of you, Superheroes have a idea what to do?

**Comment by IanDelMar** [comment]
I'll have a look on the weekend.

**Comment by szepeviktor** [comment]
> Only thing that could happen is that you have a newer version of php parser.

https://github.com/phpDocumentor/ReflectionDocBlock/issues/365

**Comment by IanDelMar** [comment]
It's not the parser...

Compare this from a [version with missing phpstan tags](https://github.com/php-stubs/wordpress-stubs/actions/runs/8673227700/job/23784356523#step:7:8232)
![image](https://github.com/php-stubs/wordpress-stubs/assets/42134098/87f9cdb5-2114-43a0-a7cf-4814e2d9e5fd)
with this from a [version with intact phpstan tags](https://github.com/php-stubs/wordpress-stubs/actions/runs/8540666008/job/23398193908)
![image](https://github.com/php-stubs/wordpress-stubs/assets/42134098/f49c7f4f-f4bb-4cdd-b76e-b262a7ec631a)
