### ISSUE TITLE
stubs for release candidates

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#17]
It would be greatly appreciated, if you could also provide the stubs of RC/release candidates, so we can check if anything changed in newer versions before they are released.

Great project!

**Comment by szepeviktor** [comment]
Thank you for your feedback!

This is all I can provide :(
You may generate stubs from any non-releases.

**Comment by kkmuffme** [comment]
Thank you.
What is the exact reason that you cannot create them here? because the beta/RC are not (tagged) in the WP github repo?

**Comment by szepeviktor** [comment]
> What is the exact reason

Here you go!

- When I got the notification that there is a new release I have to wait for Packagist cache.
- I maintain many stubs and other packages.
- John does not release them https://github.com/johnpbloch/wordpress/tags
- I don't want people to use unstable versions, not even in development.

**Comment by szepeviktor** [comment]
@kkmuffme Just for this repo and modify the release script to get WP core from elsewhere where these releases are tagged. You could have as many beta/RC releases as you want.

**Comment by kkmuffme** [comment]
Thanks
