### ISSUE TITLE
`block_template_part` parameter limited to `'header'|'footer'` when `string` should be accepted. 

### ISSUE THREAD

**Issue by lipemat** [php-stubs/wordpress-stubs#179]
[The block_template_part function](https://developer.wordpress.org/reference/functions/block_template_part/) can accept any string although the documentation suggests only 'header' or 'footer'.

To recreate:
1. Create a custom template part using the site editor.
2. Call `block_template_part` with the slug of the custom template.
3. Notice the function works.

My hunch is the documentation is referring to how WP core uses the parameter which is only 'header' and 'footer'.

Within the stubs the following is generated, but so far I have been unable to explain why.
`@phpstan-param 'header'|'footer' $part`

I created a patch which adjusts the map for this function but ends up doubling up the parameter like so.
```php
* @phpstan-param 'header'|'footer' $part
* @phpstan-param string $part
```
[block-template-part.patch](https://github.com/php-stubs/wordpress-stubs/files/15457906/block-template-part.patch)

Works but not ideal.

**Comment by szepeviktor** [comment]
@johnbillion Do you know where `@phpstan-param 'header'|'footer' $part` comes from?
Couldn't find it in this repository.

**Comment by szepeviktor** [comment]
@lipemat Thank you!
What is your specific `$part` value?

**Comment by lipemat** [comment]
Varies per project but here are some I was testing with.

1. 'test-part'
2. 'gallery'
3. 'latest-articles'

**Comment by szepeviktor** [comment]
> Do you know where `@phpstan-param 'header'|'footer' $part` comes from?

https://github.com/php-stubs/wordpress-stubs/blob/a5558fc5edcfc87750bca966d4696c41b6ec5b10/src/Visitor.php#L635

**Comment by IanDelMar** [comment]
Without losing all the 'either ... or ...' constructs, we cannot fix this in the visitor except by skipping predefined functions. So there are basically two options: 1) exclude specific functions, or 2) use the function map to override tags automatically added by identifying expressions that indicate a restricted set of possible values.

**Comment by szepeviktor** [comment]
Please do not complicate this more.
It can be resolved in local stubs.

**Comment by swissspidy** [comment]
Let's just fix this in WordPress itself :-)

https://core.trac.wordpress.org/changeset/58268

**Comment by swissspidy** [comment]
With 6.6 being released, this issue can be closed once the stubs for updated in this repo.
