### ISSUE TITLE
WP_UnitTestCase and other WordPress testing classes

### ISSUE THREAD

**Issue by SebKay** [php-stubs/wordpress-stubs#18]
WordPress stubs is great and a massive help in my day to day development!

At the moment I'm struggling with a bunch of undefined errors because I have no way of referencing (primary) the `WP_UnitTestCase` class anywhere within my plugin or theme files.

Is there the possibility of adding support for classes like `WP_UnitTestCase` in `php-stubs/wordpress-stubs`?

**Comment by szepeviktor** [comment]
Good evening, Seb!
Thank you for opening this issue.

> It provides stub declarations for WordPress core functions, classes and interfaces

This repo is simply converting WordPress core into stubs. `WP_UnitTestCase` part of WP Test Suite.
https://github.com/WordPress/wordpress-develop/blob/5.7.2/tests/phpunit/includes/testcase.php#L14

You can easily generate stubs from that with the same tool as used in this project.
Would you like me to generate one for your? I cannot promise more than that.

**Comment by SebKay** [comment]
Hey Victor,

Ah I didn't see there was a generator I could use. That looks super handy!

I'm more than happy to give it a go myself in that case.

Is there anything I need to be aware of when running the generator for the WordPress testing classes? How would you normally go about generating the stubs for the WordPress core?

**Comment by szepeviktor** [comment]
> Is there anything I need to be aware

Nothing particular. It is a huge pile of mess 😄 
You can expect collisions any other kind of inconsistency...

Simply write the finder in Symfony Finder "language" and run `vendor/bin/generate-stubs`.

**Comment by simonhammes** [comment]
@SebKay Did you manage to find a solution for this problem (e.g. running PHPStan on test files)?

**Comment by szepeviktor** [comment]
> Did you manage to find a solution

@simonhammes Here you go https://github.com/php-stubs/wordpress-tests-stubs
