### ISSUE TITLE
No more SimplePie

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#191]
```php
    ->notPath('wp-includes/SimplePie')
    ->notPath('wp-includes/class-simplepie.php')
    ->notPath('wp-includes/class-wp-feed-cache.php')
    ->notPath('wp-includes/class-wp-simplepie-file.php')
    ->notPath('wp-includes/class-wp-simplepie-sanitize-kses.php')
```

@johnbillion Is this a good idea?
You are my secret WordPress asset.

**Comment by szepeviktor** [comment]
Will a single user complain?

**Comment by johnbillion** [comment]
Is the intention to reduce the size of the stubs? If so I'm personally in favour, but it might break the PHPStan sniffing for anybody who is using SimplePie directly.

Wanna open a PR to try it?

**Comment by IanDelMar** [comment]
> Removing them doesn't make phpstan any faster, does it?

Why wouldn’t it? There’s less for PHPStan to parse. As far as I know, PHPStan traverses the entire stub file."

**Comment by szepeviktor** [comment]
Question too tough!

**Comment by szepeviktor** [comment]
@swissspidy Very sad to reopen this rabbithole.

Now we have two instances in `wp-includes/SimplePie/`.

Please vote: library/src/both/none?
Only one vote is enough, you'll be the SimplePie Dictator!

**Comment by szepeviktor** [comment]
@johnbillion Having two un-namespaced of these classes seems like a core bug.
Do you agree?

**Comment by szepeviktor** [comment]
> Having two un-namespaced of these classes seems to be a core bug.

Oh noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!

> Class SimplePie_Decode_HTML_Entities is deprecated and has not received an alias

https://github.com/simplepie/simplepie/pull/711

**Comment by swissspidy** [comment]
Wait, why are there two?

**Comment by szepeviktor** [comment]
There are two versions of SimplePie
https://github.com/WordPress/WordPress/tree/master/wp-includes/SimplePie
and there are two duplicate classes.

**Comment by IanDelMar** [comment]
![image](https://github.com/user-attachments/assets/251294d7-8f48-44c7-a4fd-1f632a6a2d89)

**Comment by swissspidy** [comment]
Weird 🙃  Background: https://core.trac.wordpress.org/ticket/55604

> As WP currently only includes the files in the library directory, I would like to suggest to continue doing so for now.
This still makes the forward-compatibility layer available as all files in the library directory now create a class alias to their namespaced version.
>
> Once 2.0.0 has been released, the files included in WP, should be switched to the files from the src directory (which is currently in place mostly to allow for Composer autoloading) and should start using the namespaced names for the SimplePie classes.

Soo... ignore `src` for now and only use `library`?

cc @sergeybiryukov

**Comment by szepeviktor** [comment]
We cannot choose other than "both".

```
Uncaught Error: Class 'SimplePie\SimplePie' not found in wordpress-stubs.php:21194
```
```php
class SimplePie extends \SimplePie\SimplePie
```
`library` uses `src`
