### ISSUE TITLE
v6.6.0 Not Showing Up in Packagist

### ISSUE THREAD

**Issue by lipemat** [php-stubs/wordpress-stubs#192]
I see version v6.6.0 is tagged and a release created, yet Packagist remains at v6.5.3 as the latest version.

https://packagist.org/packages/php-stubs/wordpress-stubs

Is there another step to get version 6.6 published?

**Comment by szepeviktor** [comment]
really

Found cached composer.json of php-stubs/wordpress-stubs (v6.5.3)
Found cached composer.json of php-stubs/wordpress-stubs (v6.5.2)
Found cached composer.json of php-stubs/wordpress-stubs (v6.5.0)
Found cached composer.json of php-stubs/wordpress-stubs (v6.4.4)
Found cached composer.json of php-stubs/wordpress-stubs (v6.4.3)
Found cached composer.json of php-stubs/wordpress-stubs (v6.4.2)
Found cached composer.json of php-stubs/wordpress-stubs (v6.4.1)
Found cached composer.json of php-stubs/wordpress-stubs (v6.4.0)
Found cached composer.json of php-stubs/wordpress-stubs (v6.3.4)
Found cached composer.json of php-stubs/wordpress-stubs (v6.3.3)

**Comment by szepeviktor** [comment]
Fixed,
Thank you.
