### ISSUE TITLE
WordPress core functions using func_get_args()

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#2]
```
apply_filters
apply_filters_ref_array
do_action
do_action_ref_array
current_user_can
#add_query_arg
wp_sprintf
add_post_type_support
get_theme_support
add_theme_support
current_theme_supports
```

List function arguments.

```bash
<func_get_args.txt xargs -I% grep '^function %(' wordpress-stubs.php
```

Issue in @phpstan https://github.com/phpstan/phpstan/issues/2599

`ignoreErrors:` https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/phpstan.neon.dist#L28-L35

**Comment by szepeviktor** [comment]
Seems to be resolved in v5.3.0

```php
function apply_filters($tag, $value)
function apply_filters_ref_array($tag, $args)
function do_action($tag, ...$arg)
function do_action_ref_array($tag, $args)
function current_user_can($capability, ...$args)
function wp_sprintf($pattern, ...$args)
function add_post_type_support($post_type, $feature, ...$args)
function get_theme_support($feature, ...$args)
function add_theme_support($feature, ...$args)
function current_theme_supports($feature, ...$args)
```

**Comment by chrisvanpatten** [comment]
@szepeviktor This seems to still be broken for me, for apply_filters calls in particular. Shouldn't the stubs show `function apply_filters($tag, ...$value)` ?

**Comment by szepeviktor** [comment]
@chrisvanpatten Yes they should.

Currently wordpress-stubs do not modify the original core source.

It should be ignored for now.

https://github.com/szepeviktor/phpstan-wordpress/blob/46fe5b16ddb3ec101c292e61e64fa094daba8bf1/example/phpstan.neon.dist#L25-L27

WP 5.3 brought a big update on correct function arguments but did not include this one.

**Comment by chrisvanpatten** [comment]
@szepeviktor I'll have to see if Psalm supports a similar type of error ignoring configuration (I really prefer it over PHPStan, sorry 😅). Would you accept a PR to fix the arguments programmatically?

**Comment by szepeviktor** [comment]
Of course, please add a `sed` command to generate.sh

**Comment by chrisvanpatten** [comment]
Actually think I got it in Psalm config:

```xml
<TooManyArguments>
  <errorLevel type="suppress">
    <referencedFunction name="apply_filters" />
  </errorLevel>
</TooManyArguments>
```

I'm going to play a bit and this might be good enough :)

**Comment by szepeviktor** [comment]
btw

- PHPStan has a brighter past and future
- XML configuration files were popular in the 2000-s
