### ISSUE TITLE
PHP8.1 "readonly" function

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#20]
As of PHP 8.1 "readonly" is a reserved keyword.

WP has a "function readonly" (as of WP 5.9/trunk it will be moved to the php-compat file and renamed in the main file).

Problem however:
the "readonly" function will be there in WP 5.9 stubs still (since it's still in WP core, just in php-compat file).

if you run psalm (phpstan?) with phpVersion=8.1, this will however trigger multiple ParseError for the stubs
(e.g. Syntax error, unexpected ')' on line 98413)

**Comment by szepeviktor** [comment]
Hello @kkmuffme!
As you may know WordPress and this package is not 100% PHP 8 compatible.

All I have for you is as follows.

```bash
sed -i -e 's#function readonly#function __readonly#' vendor/php-stubs/wordpress-stubs/wordpress-stubs.php
```

**Comment by szepeviktor** [comment]
> the "readonly" function will be there in WP 5.9 stubs still

Good news! All compat files are excluded.
I pre-exclude `php-compat` for you.

**Comment by szepeviktor** [comment]
https://github.com/php-stubs/wordpress-stubs/commit/48bb8a36c17c91d1f4b1e5eec798f6e4b4ce4a75
