### ISSUE TITLE
Remove temporary phpcs configuration for whitespace

### ISSUE THREAD

**Issue by IanDelMar** [php-stubs/wordpress-stubs#239]
This
https://github.com/php-stubs/wordpress-stubs/blob/5224a37f718048937444bc1df04f6a7d6c760d4a/phpcs.xml.dist#L15-L20
can be removed once a new version of [phpcs-psr-12-neutron-hybrid-ruleset](https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset) is released (current version: 1.1.0). The unreleased version already configures these properties (https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/pull/31).

**Comment by szepeviktor** [comment]
https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/releases/tag/v1.1.1
