### ISSUE TITLE
wp_die return type is wrong

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#248]
https://github.com/php-stubs/wordpress-stubs/blame/v6.6.2/functionMap.php#L56
- has 1 `)` too much at the end
- `array{exit: false}` is wrong, since the array can have other keys in it too, e.g. `code` and the correct type would be `array{exit: false}&array`

https://developer.wordpress.org/reference/functions/wp_die/

**Comment by szepeviktor** [comment]
@kkmuffme How many laser eyes do you have?

**Comment by IanDelMar** [comment]
> * `array{exit: false}` is wrong, since the array can have other keys in it too, e.g. `code` and the correct type would be `array{exit: false}&array`

Each of these is tested with an additional key. None of the tests are failing. Why is this?

**Comment by IanDelMar** [comment]
For PHPStan `array{exit: false}&array` = `array{exit: false}`. This is different in Psalm?

**Comment by szepeviktor** [comment]
I do not want to work on this package & I keep a distance from Psalm.

**Comment by szepeviktor** [comment]
> > I keep a distance from Psalm
> 
> Why? :-)

It has dark roots. That is all. I do not want to spark emotions.

**Comment by szepeviktor** [comment]
Sorry. That is all. I've read it on psalm.dev many years ago.

**Comment by IanDelMar** [comment]
@kkmuffme I’d appreciate it if you could have a look at #251.
