### ISSUE TITLE
non-negative-int change to int<0, max>

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#252]
e.g.
https://github.com/php-stubs/wordpress-stubs/blob/113b3f77cf7660375f106d4e404b774c2fa56efb/functionMap.php#L40

Since those `non-negative-int`, `positive-int`... are legacy types that should be phased out in favor of the more modern syntax

`int<0, max>`

**Comment by szepeviktor** [comment]
Thank you for your report.

What are those more modern things?

**Comment by szepeviktor** [comment]
Thank you for your report.

Just implemented 🍏
