### ISSUE TITLE
Type for `$query` parameter of `wpdb::prepare`

### ISSUE THREAD

**Issue by aayla-secura** [php-stubs/wordpress-stubs#260]
Using these stubs, PHPStan is reporting an error that I'm passing a non-literal string to `wpdb::prepare` because the stubs have `@phpstan-param literal-string $query` in the function declaration. I don't know whether the Wordpress code used to have that but looking at the [latest](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wpdb.php#L1452) they don't, and they accept any string.

Please consider updating the stubs for that.

**Comment by aayla-secura** [comment]
Hi there, thanks for replying. It's very impractical to enforce literal string in a database query because the database prefix, which is available in `$wpdb->prefix` is dynamic and it's not possible to hardcode this. This kind of query:

```
$wpdb->prepare("SELECT DISTINCT some_col FROM {$wpdb->prefix}some_table");
```

is entirely standard and acceptable and there's no way to make it literal.

**Comment by aayla-secura** [comment]
Hi there, thanks for replying. I don't think it's practical to enforce a literal string, since sometimes the number of template strings isn't known statically. For example if you need to query a column being `IN` a list of user-supplied values, your template string should be a comma-separated list of `%s` equal to the number of arguments. Like this

```
        $ids_template = join(',', array_fill(0, count($item_ids), '%d'));
    
        global $wpdb;
        $rows = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT DISTINCT id FROM some_table "
                . "WHERE id IN ( {$ids_template} ) ",
                $item_ids,
            )
        );

```

**Comment by craigfrancis** [comment]
Hi @aayla-secura, the `literal-string` type supports string concatenation, and works with the functions join(), implode(), array_fill(), str_repeat(), and str_pad(), which are basically string concatenation functions (the [original RFC uses this as an example](https://wiki.php.net/rfc/is_literal#where_in))... so that should work, e.g.

https://phpstan.org/r/5efeb15d-8fb1-4aad-a45f-a85bf902394e

**Comment by aayla-secura** [comment]
Ah, my bad. I simplified my code example and only included the templated string because I wrongly assumed it was that that was causing the error. It's actually using `$wpdb->prefix`: https://phpstan.org/r/fff0f27d-f22e-47de-9075-63f9deb2eff2

```php
$wpdb->prepare("SELECT id FROM {$wpdb->prefix}some_table");
```

However I can't do the following:

```php
$wpdb->prepare("SELECT id FROM %s", $wpdb->prefix}some_table");
```

because it results in SQL error due to the `%s` introducing quotes.

And I can't also use `%1$s` to avoid the quotes because it looks like numbered and unnumbered strings can't be mixed, because the remaining parameters that do need to be quoted (and therefore unnumbered) seem to start again at 1. What I mean is:

```php
$wpdb->prepare('%1$s %s', ["foo", "bar"]); // results in 'foo foo' and not 'foo bar'
```

So my actual code is:

```php
            $wpdb->prepare(
                "SELECT DISTINCT invoices.ID as invoice_id "
                . "FROM {$wpdb->prefix}getpaid_invoice_items AS items "
                . "INNER JOIN {$wpdb->posts} AS invoices ON invoices.ID = items.post_id "
                . "WHERE items.item_id IN ( {$ids_template} ) "
                . "AND invoices.post_status IN ( {$statuses_template} ) ",
                array_merge(
                    $item_ids,
                    $statuses
                )
            )
```

And I can't find a way to insert the table prefix as a literal string while avoiding it being quoted, which results in:

```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#039;&#039;wptests_getpaid_invoice_items&#039; AS items INNER JOIN &#039;wptests_posts&#039; AS invoic...&#039; at line 1]
```

Can you advise on a solution?

**Comment by szepeviktor** [comment]
How about hacking?
```php
/** @var literal-string $prefix */
$prefix = $wpdb->prefix;
```

**Comment by szepeviktor** [comment]
And modern WordPress has `%i` that does not involve quoting.
https://developer.wordpress.org/reference/classes/wpdb/prepare/

**Comment by craigfrancis** [comment]
Yep, I implemented `%i` for database identifiers (it does all of the backtick quoting/escaping for you, but it does it by the whole identifier, so its value is the prefix and table name).

I'm not at my computer at the moment, but it should be possible to note that the object property is a `literal-string`, I suspect it's just that PHPSan is assuming the value can be edited by other code, and because it's not been marked as `/** @var literal-string $prefix */`.

**Comment by aayla-secura** [comment]
@szepeviktor Oh, LOL, I had clearly not read the page properly since I didn't realize about the `%i`. Thank you, that solves my problem!

**Comment by craigfrancis** [comment]
Thanks for confirming @aayla-secura, and for your input @szepeviktor, glad to know everything is ok :-)
