### ISSUE TITLE
Generate stubs for 6.7

### ISSUE THREAD

**Issue by swissspidy** [php-stubs/wordpress-stubs#262]

**Comment by szepeviktor** [comment]
Yes Sir 🏃🏻‍♂️

**Comment by szepeviktor** [comment]
https://github.com/php-stubs/wordpress-stubs/releases/tag/v6.7.0

**Comment by IanDelMar** [comment]
`functionMap.php` needs an adjustment to prevent a duplicate return tag for `WP_Http::request()`.
