### ISSUE TITLE
Callback type for register_rest_route

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#267]
@johnbillion How does one know what is the signature for the callback in `$args['callback']`?

**Comment by szepeviktor** [comment]
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

bang 1

> This allows you to return basically any form of data.

bang 2 💣

> For more advanced usage, you can return a WP_REST_Response object.

Where is my callback handled in core?

**Comment by johnbillion** [comment]
https://github.com/WordPress/wordpress-develop/blob/d93b275c3a5bbbbaf74690c1894d54da64fb3467/src/wp-includes/rest-api/class-wp-rest-server.php#L1292
