### ISSUE TITLE
InvalidTag is not handled

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#29]
@johnbillion in `"johnpbloch/wordpress": "4.7.23"` there is an invalid param tag.
`wp-includes/class-wp-term-query.php:297:    * @param 4.6.0`

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to class@anonymous::getAdditionFromParam() must be an instance of phpDocumentor\Reflection\DocBlock\Tags\Param, instance of phpDocumentor\Reflection\DocBlock\Tags\InvalidTag given, called in /home/viktor/src/php-stubs/wordpress-stubs/visitor.php on line 113 and defined in /home/viktor/src/php-stubs/wordpress-stubs/visitor.php:178
```

https://github.com/php-stubs/wordpress-stubs/blob/master/visitor.php#L112

I'm trying to fix it...

**Comment by szepeviktor** [comment]
```php
            if (! $param instanceof Param) {
                continue;
            }
```

**Comment by szepeviktor** [comment]
Also in `visitor.php:124`

**Comment by szepeviktor** [comment]
Is it okay?
https://github.com/php-stubs/wordpress-stubs/commit/e3ab713e5403e3479f43df0217946b96d6081d37#diff-deb26a3c0625d4584d0ba7d5d16fe1f07ccb33bada8e6bedf243a0d78edda883

**Comment by johnbillion** [comment]
Haven't had a chance to check this yet, will do soon 👍

**Comment by johnbillion** [comment]
The change to `addArrayHashNotation()` looks good to me. Will you copy that change to `master` too?

**Comment by szepeviktor** [comment]
:) It is already there 22 days ago.
https://github.com/php-stubs/wordpress-stubs/blob/master/visitor.php#L112
