### ISSUE TITLE
add_meta_box() function map is not accurate

### ISSUE THREAD

**Issue by Hug0-Drelon** [php-stubs/wordpress-stubs#30]
Regarding the `add_meta_box()` [documentation](https://github.com/WordPress/wordpress-develop/blob/01ba03de1d208492608b36d21aa90a8389f32ded/src/wp-admin/includes/template.php#L998-L1028), the `$context` parameter is not limited to `"normal"|"side"|"advanced"` IMHO.
Indeed, anyone can create a new `WP_Screen` and thus define its own context for which to display meta boxes in `do_meta_boxes()` (see: https://github.com/WordPress/wordpress-develop/blob/01ba03de1d208492608b36d21aa90a8389f32ded/src/wp-admin/includes/template.php#L1247).

Source of the change: https://github.com/php-stubs/wordpress-stubs/blob/18d56875e5078a50b8ea4bc4b20b735ca61edeee/functionMap.php#L13

**Comment by szepeviktor** [comment]
Hello @Hug0-Drelon!
Thank you for using my stubs.

Please consider adding a custom stub to your PHPStan config that changes the type of `$context`.

**Comment by Hug0-Drelon** [comment]
Thanks for the answer !
I close the issue as you provided a solution.
