### ISSUE TITLE
Missing WP_HTTP_Response

### ISSUE THREAD

**Issue by AlexP11223** [php-stubs/wordpress-stubs#31]
Looks like some classes like [WP_REST_Response](https://developer.wordpress.org/reference/classes/wp_rest_response/) are missing.

**Comment by szepeviktor** [comment]
Hello @AlexP11223! 👋 
Thank you for your report.

This project is **automatically** generated from WordPress source code.
It includes almost everything.
https://github.com/php-stubs/wordpress-stubs/blob/f785ea28bfd68ef631b173f90c6047639db76d90/finder.php#L5-L38

What version of this package do you have?

**Comment by AlexP11223** [comment]
Ah, actually it is not missing. I was just confused by a Psalm error caused by other things. And I thought IDE detects these stubs, but apparently not, even though it added the dir to the project include paths.

**Comment by szepeviktor** [comment]
> by a Psalm error

You may switch to PHPStan anytime! It has great WordPress support.
