### ISSUE TITLE
Custom HTML attribute in wp_get_attachment_image() call

### ISSUE THREAD

**Issue by UVLabs** [php-stubs/wordpress-stubs#32]
I'm getting the following PHP stan error:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/10324144/167925098-95e2f879-d025-497e-9243-83f24814c2e1.png">

It looks to be due to how the function (`wp_get_attachment_image`) PHP doc is defined in https://github.com/php-stubs/wordpress-stubs/blob/master/wordpress-stubs.php

Here's how the function is being used:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10324144/167925550-074be258-05e6-47bd-93b2-741af0937ac1.png">

As per the doc this is fine...the last param should be able to take a string or array: https://developer.wordpress.org/reference/functions/wp_get_attachment_image/

@szepeviktor Are we doing something wrong?

**Comment by szepeviktor** [comment]
Hello Victor!
Thank you for your report.

It boils down to your custom HTML attribute.
Please consider adding a stubs file to your PHPStan config that fits your usage of `wp_get_attachment_image`.
I suggest to add `data-secondary` to the list of allowed string.

**Comment by szepeviktor** [comment]
I see!!!
WP core has `@param string|array $attr`
we interpret it as `@phpstan-param array{...`

**Comment by UVLabs** [comment]
> BTW I think this function cannot handle boolean attributes: $html .= " $name=" . '"' . $value . '"';
@UVLabs What is your actual HTML output?

@szepeviktor I'm not sure what you mean here? The function returns the image HTML

I've ignored the error for now but it looks like a false positive

**Comment by szepeviktor** [comment]
> I'm not sure what you mean here?

What is your current HTML code that is printed by `wp_get_attachment_image`.
E.g. `<img ...`

**Comment by UVLabs** [comment]
> > I'm not sure what you mean here?
> 
> What is your current HTML code that is printed by `wp_get_attachment_image`. E.g. `<img ... >`

@szepeviktor :

<img width="672" alt="image" src="https://user-images.githubusercontent.com/10324144/167945232-ab26bf6b-9aa9-4113-84c8-b9f13a95cf5a.png">

**Comment by szepeviktor** [comment]
Thank you!

Now it is sure that this function does not support "boolean HTML attributes".
It should be `<img ... data-secondary />`

**Comment by UVLabs** [comment]
@szepeviktor That photo was from a dump of the return, but I can see that when this renders on the page (Google Chrome) its as expected:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/10324144/167953838-c47a35cd-aed2-471c-a46d-bd9935cc1429.png">

I changed the code to instead use an array:

`wp_get_attachment_image( $gallery_attachment_ids[0], $image_size, false, array( 'class' => 'secondary-img' ) );` and PHP stan no longer throws the error

**Comment by UVLabs** [comment]
@szepeviktor I'm still not sure at this point if this was truly a false positive, the documentation is a little unclear for that particular parameter, if a string is allowed as per the wp.org doc, then there shouldn't have been error

**Comment by johnbillion** [comment]
If there's a `@param <something>|array` and it's documented with an array hash notation then the `@phpstan-param` tag gets added with the array shape. So yes, a union type gets reduced to an array shape.

**Comment by johnbillion** [comment]
The primary reason for this is parameters that accept `string|array` where the string is a URL query string which no sane person should be using to pass arguments.

**Comment by szepeviktor** [comment]
> I changed the code to instead use an array

@UVLabs Thank you for using an array!
