### ISSUE TITLE
visitor.php check for exit/die never return type

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#36]
https://php.watch/versions/8.1/never-return-type

visitor.php could check for exit/die function calls and add/fix the return type to `@return never`

**Comment by szepeviktor** [comment]
hello @kkmuffme!

Could you show me a use-case from WP core?

**Comment by kkmuffme** [comment]
For example `function wp_send_json`

**Comment by szepeviktor** [comment]
I see. https://github.com/WordPress/WordPress/blob/1d2e969b502da4b6353a6fec7a3ade8c6390b7d6/wp-includes/functions.php#L4377-L4389
Actually I don't know how to do that.

This is all I have: https://github.com/szepeviktor/phpstan-wordpress/blob/master/extension.neon#L98-L111

**Comment by kkmuffme** [comment]
Thanks. There are tons more though, if you check WP core with this rudimentary regex:
`\n(\t*)function ((?!\n\1}).)+?\s(exit|die|wp_die)[;(]`

I saw this will be tons of work to implement with visitor.php, since we essentially need to parse the whole code.

I'll go with the hardcoded phpstan list for now
