### ISSUE TITLE
Revert #38 when WordPress core supports `%i`

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#39]
...which should be v6.1.0

#38

**Comment by herndlm** [comment]
#38 should be reverted with 6.1 in October, right? Just to not add it back too early again :)

**Comment by szepeviktor** [comment]
I do not know when WP makes a new release.

**Comment by dream-encode** [comment]
This is on track for version 6.2 after being merged in https://core.trac.wordpress.org/changeset/55151.

**Comment by szepeviktor** [comment]
Thank you for the trac link.
