### ISSUE TITLE
Pluggable functions non-pluggable in stubs

### ISSUE THREAD

**Issue by mallardduck** [php-stubs/wordpress-stubs#4]
Every function from the `pluggable.php` file in WP core is wrapped in an `if ( ! function_exist )` block. The stubs for these should ideally be treated the same. This will allow use for the wordpress stubs outside of the current scope. Specifically if being applied to a larger project scope than plugin/theme alone.

**Comment by szepeviktor** [comment]
Thank you again for your suggestion.

> is wrapped in an `if ( ! function_exists )` block. The stubs for these should ideally be treated the same

Just wrap your functions overriding core functions in `function_exists`.

**Comment by szepeviktor** [comment]
core-stubs.php

```php
<?php

function apple(): void
{
    echo 'Apple is a fruit';
}
```

app.php

```php
<?php

if (! function_exists('apple')) :

function apple(): void
{
    echo 'Apple is a fruit';
}

endif;
```

`phpstan analyse -a core-subs.php -l max app.php`

```

 [OK] No errors

```

**Comment by mallardduck** [comment]
While that was one option I considered, I ruled this out as my implementation is maintained by me I'd rather mine be analysed in my project by PHPStan than use the stub implementation.

From the looks of it, this repo uses another one of @GiacoCorsiglia to generate the stubs and I'd guess this underlying library doesn't account for the functions that wp-core `if` wraps. So if they're active or around then maybe I could help fix that upstream.
However per your other comments though it seems they may not be as active to accept the PR?

**Comment by szepeviktor** [comment]
> I'd rather mine be analysed in my project by PHPStan than use the stub implementation.

Actually PHPStan does analyze **your** code..

Changing app.php to

```php
<?php

if (! function_exists('apple')) :

function apple(): void
{
    echo 'Apple is a fruit';
    return $horribleError;
}

endif;
```

produces 2 errors

```
 ------ --------------------------------------------------------------------------------------
  Line   app.php
 ------ --------------------------------------------------------------------------------------
  8      Function apple() with return type void returns mixed but should not return anything.
  8      Undefined variable: $horribleError
 ------ --------------------------------------------------------------------------------------
```

**Comment by mallardduck** [comment]
Sorry - I may be a bit confused about PHPStan's inner workings, or poorly explained.

My thought was that the areas of my code/wp-core that utilize said function would analyze it differently if it associated it with the stub vs with my implementation.

However now that I write that out I realize that's an assumption I've made about how PHPStan connects/associates different areas of code during analysis.
