### ISSUE TITLE
Expand `$args` array parameters that are described in other functions

### ISSUE THREAD

**Issue by johnbillion** [php-stubs/wordpress-stubs#46]
Basically the same as https://github.com/WordPress/wporg-developer/pull/96 but for the `@phpstan-param` tags in these stubs.

**Comment by szepeviktor** [comment]
I like this part of that PR.

![kép](https://user-images.githubusercontent.com/952007/183227496-7e2f768e-a37c-4df9-9d75-f39e0e15ee44.png)

🛷 Children cloud play on it.
But makes the code unreadable.
