### ISSUE TITLE
WordPress Constants

### ISSUE THREAD

**Issue by HowdyMcGee** [php-stubs/wordpress-stubs#5]
TBH I'm not 100% sure how stubs work but there's a few WordPress constants that are being flagged as incorrect:

ARRAY_A
ARRAY_N
OBJECT
OBJECT_K

Probably all the constants from wp-config.php and here too: 

https://github.com/WordPress/WordPress/blob/master/wp-includes/default-constants.php

**Comment by szepeviktor** [comment]
Thank you very much for your report!
I think stubs should only contain classes and functions.
Beside GiacoCorsiglia/wordpress-stubs is not updated this was the second reason to start this repo.

The problem of global constants are solved in my PHPStan extension
https://github.com/szepeviktor/phpstan-wordpress/blob/master/bootstrap.php

**Comment by szepeviktor** [comment]
Actually wpdb constants come fron the class file
https://github.com/WordPress/WordPress/blob/3d623995a8d070e608f4ff297512799cf89bb2c0/wp-includes/wp-db.php#L17-L37

**Comment by danieleperilli** [comment]
I'd like to suggest these additions:
`define( 'ARRAY_A', 'ARRAY_A');
    define( 'ARRAY_N', 'ARRAY_N');
    define( 'OBJECT', 'OBJECT');
    define( 'OBJECT_K', 'OBJECT_K');

	define( 'KB_IN_BYTES', 1024 );
	define( 'MB_IN_BYTES', 1024 * KB_IN_BYTES );
	define( 'GB_IN_BYTES', 1024 * MB_IN_BYTES );
	define( 'TB_IN_BYTES', 1024 * GB_IN_BYTES );
	
	define( 'WP_START_TIMESTAMP', 0 );
	define( 'WP_MEMORY_LIMIT', 512 );
	define( 'WP_MAX_MEMORY_LIMIT', 512);
	
	define( 'WP_DEBUG', false );
	define( 'WP_DEBUG_DISPLAY', true );
	define( 'WP_DEBUG_LOG', false );
	define( 'WP_CACHE', false );
	define( 'SCRIPT_DEBUG', '');
	define( 'MEDIA_TRASH', false );
	define( 'SHORTINIT', false );
	define( 'WP_FEATURE_BETTER_PASSWORDS', true );

	define( 'MINUTE_IN_SECONDS', 60 );
	define( 'HOUR_IN_SECONDS', 60 * MINUTE_IN_SECONDS );
	define( 'DAY_IN_SECONDS', 24 * HOUR_IN_SECONDS );
	define( 'WEEK_IN_SECONDS', 7 * DAY_IN_SECONDS );
	define( 'MONTH_IN_SECONDS', 30 * DAY_IN_SECONDS );
	define( 'YEAR_IN_SECONDS', 365 * DAY_IN_SECONDS );

    define( 'ABSPATH', '/');
    define( 'WP_CONTENT_DIR', ABSPATH . 'wp-content' );
    define( 'WP_CONTENT_URL', '/wp-content' );
    define( 'WP_PLUGIN_DIR', WP_CONTENT_DIR . '/plugins' );
    define( 'WP_PLUGIN_URL', WP_CONTENT_URL . '/plugins' );
    define( 'PLUGINDIR', 'wp-content/plugins' ); 
    define( 'WPMU_PLUGIN_DIR', WP_CONTENT_DIR . '/mu-plugins' );
    define( 'WPMU_PLUGIN_URL', WP_CONTENT_URL . '/mu-plugins' ); 
    define( 'MUPLUGINDIR', 'wp-content/mu-plugins' );

    define( 'COOKIEHASH', '' );
    define( 'USER_COOKIE', 'wordpressuser_' . COOKIEHASH );
    define( 'PASS_COOKIE', 'wordpresspass_' . COOKIEHASH );
    define( 'AUTH_COOKIE', 'wordpress_' . COOKIEHASH );
    define( 'SECURE_AUTH_COOKIE', 'wordpress_sec_' . COOKIEHASH );
    define( 'LOGGED_IN_COOKIE', 'wordpress_logged_in_' . COOKIEHASH );
    define( 'TEST_COOKIE', 'wordpress_test_cookie' );
    define( 'COOKIEPATH', '');
    define( 'SITECOOKIEPATH', '');
    define( 'ADMIN_COOKIE_PATH', SITECOOKIEPATH . 'wp-admin' );
    define( 'PLUGINS_COOKIE_PATH', '' );
    define( 'COOKIE_DOMAIN', false );
    define( 'RECOVERY_MODE_COOKIE', 'wordpress_rec_' . COOKIEHASH );
    define( 'FORCE_SSL_ADMIN', false );
    define( 'AUTOSAVE_INTERVAL', 60 );
    define( 'EMPTY_TRASH_DAYS', 30 );
    define( 'WP_POST_REVISIONS', true );
    define( 'WP_CRON_LOCK_TIMEOUT', 60 ); 
    define( 'TEMPLATEPATH', '' );
    define( 'STYLESHEETPATH', '' );
    define( 'WP_DEFAULT_THEME', '' );`

**Comment by szepeviktor** [comment]
As I've just stated above the "global world" of WordPress would pollute this project.

The repo description says: _Up-to-date WordPress function and class declaration stubs_

Please strive to use core functions instead of core constants and global variables.

**Comment by szepeviktor** [comment]
If you really need to use a core constant add it to your project/stubs manually.

Including anything other than function and class stubs would **encourage** developers to use them.

**Comment by danieleperilli** [comment]
Please consider that sometimes you can't use only core constants.

**Comment by szepeviktor** [comment]
> you can't use only core constants.

You mean using only core _functions_?

**Comment by danieleperilli** [comment]
I mean that sometimes you have to use global constants like when you use wpdb->get_results() (https://developer.wordpress.org/reference/classes/wpdb/get_results/)

**Comment by szepeviktor** [comment]
You find `$wpdb` at the end of the stubs file :)
https://github.com/php-stubs/wordpress-stubs/blob/master/generate.sh#L23-L24

**Comment by danieleperilli** [comment]
I know. The point is that when you call it, you could define an argument that could be only any of ARRAY_A | ARRAY_N | OBJECT | OBJECT_K constants.

**Comment by szepeviktor** [comment]
Yes I know that.
By adding manually these global stuff to your project keeps telling you not to use them.

I've faced this while developing the [PHPStan extension](https://github.com/szepeviktor/phpstan-wordpress/blob/master/bootstrap.php) and added them to the bootstrap file.

**Comment by danieleperilli** [comment]
I use your stubs for the intellisense of VSCode with Intelephense, so I manually created a separate file with all the constants I reported before. Probably other people do the same and having that file would be useful. Just that.

**Comment by szepeviktor** [comment]
I see.
This seem to be a Collision of Worlds :)

I'd like WordPress core to go in the OOP direction leaving PHP4/global things behind.

**Comment by szepeviktor** [comment]
@danieleperilli You know what!
I would gladly publish php-stubs/wordpress-globals with **any** global or constant.
What do you think?

**Comment by danieleperilli** [comment]
Great!

**Comment by szepeviktor** [comment]
I expect your contribution.

Please put constants and globals in the same path/file as they are in the core.

**Comment by szepeviktor** [comment]
Done.

https://github.com/php-stubs/wordpress-globals
