### ISSUE TITLE
Correctly tag releases

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#51]
Please correctly tag releases so they show up here https://github.com/php-stubs/wordpress-stubs/releases instead of here only https://github.com/php-stubs/wordpress-stubs/tags - as otherwise Github notifications don't work :-(

**Comment by szepeviktor** [comment]
Thank you for your interest in my releases!

Would you like to write a short description for each release?

**Comment by szepeviktor** [comment]
Okay!

We have 0 internal releases :)
