### ISSUE TITLE
php deprication notices in 8.1

### ISSUE THREAD

**Issue by janw-me** [php-stubs/wordpress-stubs#52]
When running php8.1 to run phpstan I get 24 Deprication notices.
I have not tested 8.0, these notices do not appear on 7.4

These can be fixed. And I'm up for that.
I've checked a couple and these fixed will cause errors when lower then running php7.0.

So would you be open for a PR with these fixes of 8+ notices at the cost of dropping support of 5.6 and lower.

To be clear, I'm not talking about the version you set in `phpstan.neon.dist` I'm talking about the php cli version.

**Comment by janw-me** [comment]
Yes

**Comment by szepeviktor** [comment]
I would gladly include a bunch of `sed` commands.

**Comment by janw-me** [comment]
That's not a bad idea. I'll see if I can fix that this week.

**Comment by szepeviktor** [comment]
Like this one.
https://github.com/php-stubs/acf-pro-stubs/blob/7e44b653bd72e5eebf725f3af6b5afaae3039dcf/generate.sh#L30-L43

It is **easier** to work on WordPress source *before* stubs generation.

**Comment by szepeviktor** [comment]
You find the Request v1 package in `wp-includes/Requests/`

**Comment by janw-me** [comment]
:+1: Thanks I'll take a look.
I'll manage
