### ISSUE TITLE
Incorrect stubs since >5.9.3 + mismatch between packagist.org and GitHub

### ISSUE THREAD

**Issue by calvinalkan** [php-stubs/wordpress-stubs#57]
There seems to be something broken since the 5.9.4 release. 

I noticed this because psalm started to report missing classes from the included PHPMailer package. 

v5.9.3 has the correct stubs for PHPMailer, since 5.9.4 they are missing. 

Check out the two branches in this reproduction repo:

https://github.com/calvinalkan/stubs-bug

Now, here comes the weird part. 

The file in the GitHub repo:

https://raw.githubusercontent.com/php-stubs/wordpress-stubs/master/wordpress-stubs.php

**does** contain the PHPMailer namespace.

So there seems to be a mismatch between the code in the GitHub repo and the code that is downloaded from packagist. 

I have no idea why this is happening. Maybe you can try synching the package again in the packagist UI

**Comment by calvinalkan** [comment]
This was the CI run that made me aware of this:

https://github.com/snicco/snicco/actions/runs/3209808684/jobs/5246867039#step:6:858

**Comment by calvinalkan** [comment]
Successful CI run after locking the stubs to 5.9.3

https://github.com/snicco/snicco/actions/runs/3210152049/jobs/5247397225

**Comment by szepeviktor** [comment]
Thank you for your report.

These was a mountain of problems here in the repo.
I have to shovel away the remnants.

**Comment by szepeviktor** [comment]
Packagist is on non-tagged commit
https://github.com/php-stubs/wordpress-stubs/commit/8f696e429e375ef40a841ecf5ac686ff7437b4dc

I've pressed "Update" on packagist.org, may that will resolve this issue.

**Comment by calvinalkan** [comment]
What kind of other problems are/were present here?

Can you open issues?

Missing stubs here will break all downstream dependents of 

https://github.com/snicco/php-scoper-wordpress-excludes as well which will lead to broken scoped packages with PHP-Scoper

**Comment by szepeviktor** [comment]
If it succeeds you have to issue `composer clear-cache` command.

**Comment by calvinalkan** [comment]
[PHPScoper stubs seem to be correct still for 6.0.1](https://github.com/snicco/php-scoper-wordpress-excludes/blob/6.0.1/generated/exclude-wordpress-classes.json#L55)

But I don't know about other classes that might be missing, only wound this through a random psalm failure in https://github.com/snicco/better-wp-mail

**Comment by szepeviktor** [comment]
> What kind of other problems are/were present here?

My experiments for excluding code available in packages remained in my `vendor/` directory and generated stubs did not include certain classes, e.g. PHPMailer.

**Comment by calvinalkan** [comment]
> > What kind of other problems are/were present here?
> 
> My experiments for excluding code available in packages remained in my `vendor/` directory and generated stubs did not include certain classes, e.g. PHPMailer.

Okay, but why did this get tagged in packagist?

**Comment by szepeviktor** [comment]
All tags are picked up my Packagist automatically.

Please see  #11

**Comment by szepeviktor** [comment]
> Okay, but why did this get tagged in packagist?

PHPMailer remaind in my vendor/ so it was not included in stubs. The generator has this feature not to include loaded classes.

**Comment by szepeviktor** [comment]
https://github.com/php-stubs/wordpress-stubs/releases/tag/v6.0.2 points to https://github.com/php-stubs/wordpress-stubs/commit/165b84f082db851e76ec51bebcde550d03976893 but Packagist know about the previous incorrect tag:

```
$ wget -qO- https://packagist.org/packages/php-stubs/wordpress-stubs.json|jq -r '."package"."versions"."v6.0.2"."dist"'
{
  "url": "https://api.github.com/repos/php-stubs/wordpress-stubs/zipball/8f696e429e375ef40a841ecf5ac686ff7437b4dc",
  "type": "zip",
  "shasum": "",
  "reference": "8f696e429e375ef40a841ecf5ac686ff7437b4dc"
}
```

**Comment by szepeviktor** [comment]
I hope the best.

![kép](https://user-images.githubusercontent.com/952007/194705841-fc893bf0-03f6-4055-9482-49beef5399b3.png)

**Comment by calvinalkan** [comment]
> [All tags](https://github.com/php-stubs/wordpress-stubs/blob/165b84f082db851e76ec51bebcde550d03976893/release-latest-versions.sh#L31) are picked up my Packagist automatically.
> 
> Please see #11

So what is the expected behavior now?

IMO they should be included, WordPress forces you to use those classes, and many plugins (must) do it.

One example is the hook phpmailer_init in wp_mail which many plugins require to properly configure emails.

**Comment by szepeviktor** [comment]
> they should be included

Of course!
This is my error.
Git tags have been overwritten.

**Comment by szepeviktor** [comment]
@calvinalkan Very good news! 🎉 
New tags are public 🎈 

https://github.com/php-stubs/wordpress-stubs/issues/57#issuecomment-1272294874

**Comment by szepeviktor** [comment]
Thank you for opening this issue.
