### ISSUE TITLE
DocblockTypeContradiction with get_settings_errors()

### ISSUE THREAD

**Issue by mcaskill** [php-stubs/wordpress-stubs#59]
The [`get_settings_errors()`](https://developer.wordpress.org/reference/functions/get_settings_errors/) returns an array of setting errors but WordPress' docblock incorrectly [returns a single setting error][1] which causes a contradiction such as in Psalm:

```
ERROR: DocblockTypeContradiction - includes/class-admin-controller.php:262:7 - Operand of type false is always false (see https://psalm.dev/155)
	    	! get_settings_errors( self::OPTIONS_KEY )
```

I've [submitted a ticket with a patch][2] to address it.

Until then, is there a way to introduce exceptions within this package?

```diff
   * }
-  * @phpstan-return array{
-  *   setting: string,
-  *   code: string,
-  *   message: string,
-  *   type: string,
-  * }
-  */
+  * @phpstan-return array<int|string, array{
+  *   setting: string,
+  *   code: string,
+  *   message: string,
+  *   type: string,
+  * }>
   */
  function get_settings_errors($setting = '', $sanitize = \false)
```

[1]: https://core.trac.wordpress.org/changeset/48760
[2]: https://core.trac.wordpress.org/ticket/57323

**Comment by szepeviktor** [comment]
Hello @mcaskill! 👋🏻 
Thank you for your report.

Stubs are automatically generated.
There are two files in the root: generator and visitor.
How would you introduce this change?

**Comment by mcaskill** [comment]
> How would you introduce this change?

With [psalm/psalm-plugin-wordpress](https://github.com/psalm/psalm-plugin-wordpress), the solution so far has been add new type information to a [stubs override file](https://github.com/psalm/psalm-plugin-wordpress/blob/2.1.0/stubs/overrides.php). I recently started tinkering with that file but there's issues with it.

> You can add an entry to functionMap.php with the correction […]

Thanks for the information. I had not looked into the specific details of how this package builds the stubs.

> […] but to be honest if I were you I would just place the correction in your application code.

I agree. Especially, _if_ the ticket might be merged in time for the next maintenance release of WordPress or a few years from now.

**Comment by mcaskill** [comment]
My ticket on the WordPress Trac has been [merged](https://core.trac.wordpress.org/changeset/54963), thanks to @johnbillion.
