### ISSUE TITLE
Does anyone know when Request v2 will be part of core?

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#60]
https://core.trac.wordpress.org/changeset/54997 👀

Need to update this: https://github.com/php-stubs/wordpress-stubs/blob/19e7966c8e70a99a4824b3e5d1526680a151f13b/generate.sh#L39-L72

**Comment by swissspidy** [comment]
In [WordPress 6.2](https://make.wordpress.org/core/6-2/), scheduled for release on March 28

**Comment by szepeviktor** [comment]
Now! Please into #71
