### ISSUE TITLE
Why globals are not included?

### ISSUE THREAD

**Issue by Mister-Stein** [php-stubs/wordpress-stubs#63]
The question as in title: why globals are not included? They would be handy, because some WordPress plugins are using globals. Without stubs with globals, the tool I use for static code analysis will not be able to resolve them in analyzed code.

**Comment by szepeviktor** [comment]
Thank you for your question. It is a good one!
This is how I think about WordPress plugins, themes.
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
Please see the _What to avoid_ list.

Many asked for globals. https://github.com/php-stubs/wordpress-globals

**Comment by Mister-Stein** [comment]
I get your idea @szepeviktor, and I support it. I think that plugin developers should comply with it.
Much thanks for providing stubs with globals anyway, even though if they outdated.

**Comment by szepeviktor** [comment]
@Mister-Stein Would you be the maintainer of that repo?

**Comment by Mister-Stein** [comment]
That is a nice proposition, it would be honor for me. But I'm afraid that I might be not enough competent for that. I don't have such in-depth knowledge in WordPress, especially the core, I'm still learning it, and only recently I've learned the basics of PHP, so I could understand the code. So, I'm sorry that I'm not suitable for this.

**Comment by szepeviktor** [comment]
All right.
You see? This is why this repo is unmaintained.
