### ISSUE TITLE
How to avoid getting errors for drop-in classes?

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#7]
e.g. class WP_Object_Cache dropin overwrites the native class.

If you now redefine a function, e.g. flush to accept 2 instead of 1 arg (like WP default), it will obviously give an error now.

Is there any way to solve this?

**Comment by szepeviktor** [comment]
Thank you for your issue.

All WordPress compatible plugin/theme/package will call WP_Object_Cache methods with the original arguments.

Could you show me your drop-in?

**Comment by kkmuffme** [comment]
before flush accepted 1 arg (timeout), then WP changed it to 0 args.

However it's allowed to use a custom drop in with whatever many optional args you want.
e.g.

```
public function flush( $deprecated = 0, $string = '' ) {
```

where $string is a custom implementation to flush only specific keys that match a string.

**Comment by szepeviktor** [comment]
The only way out it to move WP_Object_Cache to another file and optionally include it static analysis. This would hurt all users of the packages.

Please add these to `ignoreErrors:`
Thanks.

**Comment by szepeviktor** [comment]
WordPress' conditional definitions are not OOP friendly :(

**Comment by kkmuffme** [comment]
Actually a working solution is: remove the WP_Object_Cache class from the stubs file.

I can just remove this myself for my use case, but perhaps it would make sense to offer stubs that exclude certain drop in classes? (mainly: object cache actually)

**Comment by szepeviktor** [comment]
> it would make sense to offer stubs that exclude certain ...

WordPress core includes "millions" of conditional definitions.
It would split the one stubs file to 1 zillion small and use less files to support conditional definitions: `if ( ! function_exists( 'wp_foo' ) ) { function wp_foo() ...`

**Comment by szepeviktor** [comment]
```bash
sed -i -e 's#^class WP_Object_Cache$#class __WP_Object_Cache#' wordpress-stubs.php
```
