### ISSUE TITLE
Check if function exists in wordpress-stubs.php

### ISSUE THREAD

**Issue by benjaminniess** [php-stubs/wordpress-stubs#70]
Hello,

When using WordPress as a composer dependency (with Bedrock), the phpstan command results to

Fatal error: Cannot redeclare wp_hash_password() (previously declared in xxx/vendor/roots/wp-password-bcrypt/wp-password-bcrypt.php:70). It is the same for `wp_check_password` and `wp_set_password`

The workaround I found is to encapsulate them with a `function_exists` in the `wordpress-stubs/wordpress-stubs.php`. Do you think you could add this to the code? I can make a PR if you want.

Thanks

**Comment by szepeviktor** [comment]
Welcome to PHP Stubs, Benjamin! 👋🏻 

WordPress core uses something called conditional definition to override functions.
There is no solution for that :(

Work-around No1: remove `wp-password-bcrypt.php` or the whole package before analysis
Work-around No2: `sed -i -e 's#function wp_hash_password#function __wp_hash_password#' vendor/php-stubs/wordpress-stubs/wordpress-stubs.php`

📚 sed -i -e 's#function wp_hash_password#function __wp_hash_password#' vendor/php-stubs/wordpress-stubs/wordpress-stubs.php

**Comment by johnbillion** [comment]
I've given a couple of workshops on WordPress+PHPStan and both times this exact problem was the first to arise. We determined that the most correct solution is for the Bedrock bcrypt library to wrap its functions in `function_exists()` checks because it has no way to ensure that another definition of one of those functions isn't loaded by another plugin. I'm not sure why that is not the case.

**Comment by johnbillion** [comment]
See also #4.

**Comment by johnbillion** [comment]
Also Viktor is everywhere: https://github.com/roots/wp-password-bcrypt/issues/11

**Comment by szepeviktor** [comment]
> Active installations: 4,000+

This is unbelievable.
People keep downloading that plugin from WP.org.

**Comment by benjaminniess** [comment]
Thank you very much for you fast replies 🙏  I understand now and I've chosen the `sed` workaround
