### ISSUE TITLE
WordPress 6.2 in WordPress any more

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-stubs#71]
Too many things have changed 🤯 

Help!

**Comment by szepeviktor** [comment]
@johnbillion Would you depend on https://github.com/WordPress/Requests and exclude `wp-includes/Requests/*`?

**Comment by johnbillion** [comment]
`visitor62.php` and `functionMap62.php`? Please Lord have mercy on our souls.

**Comment by szepeviktor** [comment]
Much better then abandoning all my packages for WordPress.

**Comment by johnbillion** [comment]
Regarding the Requests library, I think continuing to scan and include the library that ships with core makes sense. If someone runs a Composer project which depends on `rmccue/requests` as well as WordPress, then I think they'll get a redeclaration error in PHPStan, but that's already the case with PHPMail, ID3, etc.

**Comment by johnbillion** [comment]
> What is your suggestion?

I'll take a look at the weekend. I think we can introduce some more conditional logic that doesn't require duplicating those two files.

**Comment by szepeviktor** [comment]
Implemented in #85
