### ISSUE TITLE
functionMap.php wrong

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#72]
https://github.com/php-stubs/wordpress-stubs/commit/ac0c474fda8a2d2b87a793f5ab85bc13bb87964f

the functionMap changes here seem to be mostly wrong - the param is called $index not $offset for e.g. `offsetExists`

Then for some reason there is a new functionMap file created for 6.2 where those changes are missing altogether?

**Comment by szepeviktor** [comment]
> the param is called $index not $offset for e.g. `offsetExists`

I see `$offset`
https://github.com/WordPress/WordPress/blob/17e2eff4aa3beb2802cbec12b6f08e2fbf69893d/wp-includes/rest-api/class-wp-rest-request.php#L962
What do you think?

**Comment by szepeviktor** [comment]
> Then for some reason there is a new functionMap file created for 6.2 where those changes are missing altogether?

I would like to delete this package for some reasons. That makes me almost blind for everything related to this package.

Thank you for noticing it.

https://github.com/php-stubs/wordpress-stubs/commit/b73fe99eadf9fb56363619dac0343b6d19907dce

**Comment by szepeviktor** [comment]
> the param is called $index not $offset for e.g. `offsetExists`

I see!

Is this the solution? https://github.com/php-stubs/wordpress-stubs/commit/dc638ef936aaf610097258b3d4fce9ab47c73402
