### ISSUE TITLE
WP_CLI stubs

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#8]
First of, great great repo that helps getting WP plugins properly checked.

Would it be possible to add stubs for the WP_CLI class?
As I have a few plugins that add a WP_CLI (sub)command. (which are now reported as UndefinedClass bc of missing stub)

**Comment by szepeviktor** [comment]
Yes!

Would you like to contribute the stubs and the tooling?

**Comment by szepeviktor** [comment]
You may have noticed there are a lot of stubs generator in the PHPStan Extension: https://github.com/szepeviktor/phpstan-wordpress/blob/master/stub-generators/wp-cli-generate-stubs.sh

**Comment by kkmuffme** [comment]
Honestly, its way over my head already, as I just started using psalm/phpstan and I just need to try to get things working for me on a base level before I can contribute :-(
Once I have it figured out and solved the gazillion of issues in my code base I'd be happy to help reply/solve any issues though

**Comment by szepeviktor** [comment]
- Please see the readme https://github.com/szepeviktor/phpstan-wordpress/blob/master/README.md
- open an issue
- or write me an email if you need a couple of hours of hand-on help

**Comment by leonstafford** [comment]
@kkmuffme how did you get on with this? 

Here is an example of stubs from the generator @szepeviktor mentioned in previous comment to you in one of my repos: https://github.com/WP2Static/static-html-output-plugin/blob/master/tests/phpstan/wp-cli-stubs-2.2.0.php

If it's a bit daunting to generate the stubs yourself, you may be able to start by copying mine and seeing how it's used with `autoload_files` in `phpstan.neon` (note: that exact syntax may change with some recent PHPStan updates, but has been working well for me. 

For a less legit way to do it, you could also require `"wp-cli/wp-cli-bundle": "*"` in your composer's `require-dev` section. This will silence most errors, but still faced some for `WP_CLI\Utils` when I tried for `format_items` and `make_progress_bar`. You'd also want to make sure you don't bundle that up in your plugin's installer.

> or write me an email if you need a couple of hours of hands-on help

That's yet another generous offer from Viktor - he's volunteered many hrs helping me with several things and is a real expert to learn from - jump on it if you can! You can also feel free to ask me and will do my best to help.

**Comment by kkmuffme** [comment]
I decided to abandon the stubs alltogether as I got so many false positives from psalm it wasted my time.
Maybe looking into it again in the future and will contact szepeviktor for some paid help to get it set up & issues solved.
Perhaps it's also psalm related and phpstan works better

**Comment by szepeviktor** [comment]
Executed by @Mte90

https://github.com/php-stubs/wp-cli-stubs
