### ISSUE TITLE
Undefined function errors

### ISSUE THREAD

**Issue by kkmuffme** [php-stubs/wordpress-stubs#9]
I get undefined function errors for loads of function in my plugin, e.g. when using wc_get_product within my plugin.

Is there any way to solve this (without generating woocommerce stubs)?

EDIT: wouldnt it make more sense to use a clone WP repo with all dependency plugins and use an autoloader instead of stubbing like we do now? This would resolve this problem, wouldn't it?

**Comment by szepeviktor** [comment]
Yes, there is: https://github.com/php-stubs/woocommerce-stubs#readme

**Comment by szepeviktor** [comment]
> use an autoloader instead of stubbing like we do now?

Code in the WordPress ecosystem contains a lot of [side-effects](https://www.php-fig.org/psr/psr-1/#23-side-effects) so we need stubs.

**Comment by szepeviktor** [comment]
Closing for now.

Feel free to reopen, to comment.
